type Query {
  mine: GeoResult!
}

type GeoResult {
  lat: Float
  lng: Float
  accuracy: Float
  tz: String
  country: String
  countryName: String
  subdivision: String
  subdivisionName: String
  cityName: String
  postalCode: String
  isp: String
  organization: String
  ip: String
}
