# fly.toml file generated for codeday-gql on 2023-05-24T10:12:53-07:00

app = "codeday-gql"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sea"

[experimental]
  auto_rollback = true

[env]
  ACCOUNT_URL = "http://top1.nearest.of.codeday-account-gql.internal:5000/graphql"
  ADVISORS_URL = "http://top1.nearest.of.codeday-advisors-gql.internal:5000/graphql"
  CALENDAR_URL = "http://top1.nearest.of.codeday-calendar-gql.internal:5000/graphql"
  CLEAR_URL = "http://top1.nearest.of.codeday-clear-gql.internal:5000/graphql"
  LABS_URL = "http://top1.nearest.of.codeday-labs-gql.internal:5000/graphql"
  SHOWYOURWORK_URL = "http://top1.nearest.of.codeday-discord-gql.internal:5000/graphql"
  WORDPRESS_URL = "http://top1.nearest.of.codeday-wp.internal/graphql"

[[services]]
  protocol = "tcp"
  internal_port = 4000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 50
    soft_limit = 40

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
