# fly.toml file generated for codeday-gql on 2021-11-18T11:19:32-05:00

app = "codeday-gql"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  ACCOUNT_URL = "http://top1.nearest.of.codeday-account-gql.internal:5000/graphql"
  ADVISORS_URL = "http://top1.nearest.of.codeday-advisors-gql.internal:5000/graphql"
  CALENDAR_URL = "http://top1.nearest.of.codeday-calendar-gql.internal:5000/graphql"
  CLEAR_URL = "http://top1.nearest.of.codeday-clear-gql.internal:5000/graphql"
  LABS_URL = "http://top1.nearest.of.codeday-labs-gql.internal:5000/graphql"
  SHOWYOURWORK_URL = "http://top1.nearest.of.codeday-discord-gql.internal:5000/graphql"
  WORDPRESS_URL = "http://top1.nearest.of.codeday-wp.internal/graphql"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 4000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 50
    soft_limit = 40
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
