type User {
  id: ID!
  blocked: Boolean
  email: String
  username: String
  picture(transform: UserPictureTransformInput): String
  givenName: String
  familyName: String
  name: String
  title: String
  bio: String
  discordId: String
  acceptTos: Boolean
  displayNameFormat: String
  phoneNumber: String
  pronoun: String
  roles: [UserRole]
  badges: [UserBadge]
  discordInformation: DiscordInformation
}

input UpdateUserInput {
  blocked: Boolean
  email: String
  username: String
  givenName: String
  familyName: String
  title: String
  bio: String
  phoneNumber: String
  pronoun: String
}

type UserBadge {
  id: ID!
  expiresUtc: String
}

input UserBadgeInput {
  id: ID!
  expiresUtc: String
}

type UserRole {
  id: ID!
  name: String!
  description: String
}

type DiscordInformation {
  username: String!
  discriminator: String!
  avatar: String
}

enum UserPictureFit {
  CLAMP,
  CLIP,
  CROP,
  FACEAREA,
  FILL,
  FILLMAX,
  MAX,
  MIN,
  SCALE,
}

input UserPictureTransformInput {
  width: Int
  height: Int
  fit: UserPictureFit
}

input UserSingleInput {
  id: ID
  username: String
  email: String
  discordId: String
}

input UserSearch {
  givenName: String
  familyName: String
  name: String
  username: String
}

type Query {
  getUser(where: UserSingleInput!, fresh: Boolean): User
  searchUsers(where: UserSearch!): [User]!
  roleUsers(roleId: String!): [User]!
}

type Mutation {
  updateUser(username: String!, updates: UpdateUserInput!): Boolean
  grantBadge(username: String!, badge: UserBadgeInput!): Boolean
}
